### ISSUE TITLE
import Image, ImageEnhance

### ISSUE THREAD

**Issue by lzanuz** [codekoala/django-watermark#10]
Hello,

Why:  import Image, ImageEnhance

Instead:  from PIL import Image, ImageEnhance

--------

I needed to do this for import directly Image and ImageEnhance:

import sys
from PIL import Image, ImageEnhance
sys.modules['Image'] = Image
sys.modules['ImageEnhance'] = ImageEnhance

**Comment by bashu** [comment]
fixed in "develop" branch
