### ISSUE TITLE
A problem with an image filenames with spaces

### ISSUE THREAD

**Issue by lynx-r** [codekoala/django-watermark#2]
I have a problem with filenames with spaces. I got error:
[Errno 2] No such file or directory: '/path/to/image%20with%20spaces.png'
I solved it by unquoting url on line 98 in file watermarker/templatetags/watermark.py
 97         # make sure URL is a string
 98         import urllib2
 99         url = urllib2.unquote(str(url))

**Comment by bashu** [comment]
fixed in "develop" branch
