### ISSUE TITLE
relative size of watermark

### ISSUE THREAD

**Issue by tarokinoe** [codekoala/django-watermark#20]
I apply watermark to images which have different size. On middle size images watermark look nice, on small images it overlay, on big images it is hard to discer.  Is there any possibility to set watermark size relatively to target image?

**Comment by lzanuz** [comment]
Hi @bashu  @tarokinoe 
I had this same problem and I developed this functionality on my fork, just look that and reintegrate if you think that its right or change it if you have a better idea.
By.

**Comment by bashu** [comment]
@lzanuz I will look at it and TIA

**Comment by bashu** [comment]
to @tarokinoe pass scale option like this ``scale=R33%``
