### ISSUE TITLE
Your connection attempt failed for user 'root' from your host to server at localhost:3306:   Can't connect to MySQL server on '127.0.0.1' (61)

### ISSUE THREAD

**Issue by pngimbwa** [codekoala/django-watermark#23]
Hello, 

Am getting the following error message when I try to open my connections in mysql workbench.Am using Mysql workbench 6.3 (64 -bits)

The error message:
Your connection attempt failed for user 'root' from your host to server at localhost:3306:   Can't connect to MySQL server on '127.0.0.1' (61)
Please:
 1 Check that mysql is running on server localhost
 2 Check that mysql is running on port 3306 (note: 3306 is the default, but this can be changed)
 3 Check the root has rights to connect to localhost from your address (mysql rights define what  
    clients can connect to the server and from which machines) 
 4 Make sure you are both providing a password if needed and using the correct password for  
    localhost connecting from the host address you're connecting from

Help would be much appreciated.

Thank you,

Peter

**Comment by bashu** [comment]
1) check `ps aux | grep mysql` or `/etc/init.d/mysql status`
2) check `telnet localhost 3306`
3 and 4) check `mysqladmin -u username -p password`

**Comment by pngimbwa** [comment]
How do I check /etc/init.d/mysql status? I can't find that path.
More help please.

**Comment by bashu** [comment]
open terminal / console and run command `/etc/init.d/mysql status`

**Comment by pngimbwa** [comment]
It tells me no such file or directory when i run that command

**Comment by bashu** [comment]
do  you have mysql server installed?

**Comment by pngimbwa** [comment]
Yes, I have installed mysql 5.6.26

**Comment by pngimbwa** [comment]
Actually I have installed MySQL Community Server and MySQL Workbench

**Comment by bashu** [comment]
http://dev.mysql.com/doc/refman/5.6/en/
