### ISSUE TITLE
drop down menu show selected item when page refreshes in django

### ISSUE THREAD

**Issue by pngimbwa** [codekoala/django-watermark#25]
Hi, 
Am new in django programming, I would like to know how to retain the value from dropdown menu when submitting the form, then come back with errors which shows other field are can't be empty. 

Here are my codes:

< <select name='CropGroupName' id="inputCropGroup">
        <option value="null">Choose</option>
        {% for group in getcropgroup %}
        <option value="{{group.groupname}}" >{{group.groupname}}</option>
        {% endfor %}
      </select>

Thanks in advance

**Comment by bashu** [comment]
https://docs.djangoproject.com/en/1.8/intro/
