### ISSUE TITLE
Exception in django 1.9

### ISSUE THREAD

**Issue by amigo00678** [codekoala/django-watermark#27]
this line should be changed
https://github.com/bashu/django-watermark/blob/develop/watermarker/templatetags/watermark.py#L167

to
`if modified >= make_aware(watermark.date_updated, get_default_timezone()):`

or it gives django 'time aware' comparison exception.

**Comment by gridlined** [comment]
@papenx Was this issue fixed via PR #33?

**Comment by papenx** [comment]
@gridlined yeah

**Comment by bashu** [comment]
closed via 8d0a848bfe063478f3f5c6bdd253ff6793ff21dd

**Comment by bashu** [comment]
to @papenx you can use upstream version again
