### ISSUE TITLE
Not working with Pilow >= 4.2.0

### ISSUE THREAD

**Issue by lzanuz** [codekoala/django-watermark#31]
OSError: cannot write mode RGBA as JPEG

References:

https://github.com/python-pillow/Pillow/issues/2609
https://www.bountysource.com/issues/46873548-cannot-write-mode-rgba-as-jpeg-4-2-0

**Comment by lzanuz** [comment]
Easy way to solve, git diff:

```
-    def create_watermark(self, target, mark, fpath,
-                         quality=QUALITY, **kwargs):
+    def create_watermark(self, target, mark, fpath, quality=QUALITY, **kwargs):
         """
         Create the watermarked image on the filesystem
         """
         im = utils.watermark(target, mark, **kwargs)
+        if target.format == 'JPEG' and im.mode.endswith('A'):
+            im = im.convert(im.mode[:-1])
         im.save(fpath, quality=quality)
         return im
```

**Comment by Nifled** [comment]
@lzanuz Where would that code go? Or is that a solution to a `create_watermark` method in the core files? I'm currently using this project and that error keeps popping up.

**Comment by lzanuz** [comment]
Here:
https://github.com/bashu/django-watermark/blob/develop/watermarker/templatetags/watermark.py#L251

**Comment by bashu** [comment]
I guess it was fixed in https://github.com/bashu/django-watermark/pull/39
