### ISSUE TITLE
Request: Release 0.1.9 to PyPI

### ISSUE THREAD

**Issue by khink** [codekoala/django-watermark#40]
Hi @execut ,

Thanks for your work on maintaining this project!

I saw in https://github.com/bashu/django-watermark/blob/develop/CHANGES that a 0.1.9 release has been tagged. It's not yet on https://pypi.org/project/django-watermark/#history, however. Can you do that, or should we ask someone else?

Thanks in advance!

Regards, 

Kees

**Comment by execut** [comment]
Hi @khink
I can not do this. Most likely it can be done by @Bashu

**Comment by bashu** [comment]
to @khink done, please re-run `pip install -U django-watermark`

**Comment by khink** [comment]
Thank you @bashu!
