### ISSUE TITLE
Actual watermark sample code in dynamically generated images list.

### ISSUE THREAD

**Issue by sunjoomoon** [codekoala/django-watermark#5]
Hi from below, I wish to apply watermark to dynamically generated images, what will be the code? I see instruction sample code does seem to be compatible. Thanks. Cheers.

{% if object.picture %}
<h2 class="headerx">{% trans "Product Photos" %}</h2>
<div class="photos-details">                              
<ul>                                               
{% for item in object.coimage_set.all %}
<li>
<img src="{% thumbnail item.picture 620x500 %}" alt="{{ item.name }} "  />
<h3>{{ item.name }}</h3>
<p class="product-desc">{{ item.description }}</p>
</li> 
{% empty %}
<li>{% trans "There are no images yet" %}</li>
{% endfor %}
</ul>
</div>

**Comment by bashu** [comment]
and what is a problem?
