### ISSUE TITLE
URL NOT DIRECTING PROPERLY

### ISSUE THREAD

**Issue by skizzy** [codekoala/django-watermark#6]
Hello,

I successfully installed django-watermark. After setting it up, I load up the webpage. On Chrome browser, it's working fine and images are watermarked. On Mozilla firefox and Opera, it's not displaying any images not even the one I uploaded. After checking the source code, I found out that '\' after "watermarked" is the one causing the problem. 

```
   <li><img src=/media//photos/watermarked\3bbb94f57f32d2796ea59adc86310a12752f0088.jpg> </li>
```

Template

```
  <li><img src={{ MEDIA_URL }}/{{post.main_view|watermark:"hall,position=tl,opacity=90"}}> </li>
```

I've been looking for a way to fix this, yet no success. Please any idea on how I can fix this?

**Comment by bashu** [comment]
too old...
